services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3004"
    working_dir: /app
    command: "bun run start"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:3005"
    working_dir: /app
    command: ["bun", "preview"]
    # volumes:
    #   - ./frontend:/app
    environment:
      - NODE_ENV=production
      - PORT=4173
